MAINFLUX_IP = "10.0.0.100"
MAINFLUX_PORT = "80"
MAINFLUX_URL = "http://{}:{}".format(MAINFLUX_IP, MAINFLUX_PORT)
DB_READER_IP = MAINFLUX_IP
DB_READER_PORT = "8905"
DB_READER_URL = "http://{}:{}".format(DB_READER_IP, DB_READER_PORT)
MAINFLUX_USER_EMAIL = "tks@tks.ru"
MAINFLUX_USER_PASSWORD = "T_K_S486"
